version: '3'
services:
  app-db:
    image: mariadb
    container_name: cctv-data-kiel.prod.db
    env_file:
      - .env
    ports:
      - 3337:3306
    volumes:
      - ./.docker:/var/lib/mysql
    networks:
      - cctv-data-kiel.prod.network

  web:
    build:
      context: .
    container_name: cctv-data-kiel.prod.web
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/var/www/cctv-data-kiel.itsgitz.com/
    networks:
      - cctv-data-kiel.prod.network

  server:
    image: nginx
    container_name: cctv-data-kiel.prod.server
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/cctv-data-kiel.itsgitz.com/
    ports:
      - 127.0.0.1:8005:80
    networks:
      - cctv-data-kiel.prod.network

networks:
  cctv-data-kiel.prod.network:
    name: cctv-data-kiel.prod.network
    driver: bridge
